import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { NextThemeProvider } from "@/provider/NextThemeProvider";
import NavLayout from "@/common/Navbar/NavLayout";
import { TableProvider } from "@/provider/TableProvider";
import { ProductProvider } from "@/provider/ProductProvider";
import Footer from "@/common/Footer/Footer";

const inter = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextThemesProvider attribute="class" defaultTheme="dark">
          <NextThemeProvider>
              {children}
          </NextThemeProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
